// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declQuad(c+1,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+3,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declArray(c+5,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->pushPrefix("multiplier", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declQuad(c+9,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+11,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declArray(c+13,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+17,0,"pp0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+21,0,"pp1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+25,0,"pp2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+29,0,"pp3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+33,0,"pp4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+37,0,"pp5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+41,0,"pp6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+45,0,"pp7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+49,0,"pp8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+53,0,"pp9",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+57,0,"pp10",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+61,0,"pp11",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+65,0,"pp12",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+69,0,"pp13",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+73,0,"pp14",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+77,0,"pp15",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+81,0,"pp16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+85,0,"pp17",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+89,0,"pp18",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+93,0,"pp19",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+97,0,"pp20",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+101,0,"pp21",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+105,0,"pp22",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+109,0,"pp23",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+113,0,"pp24",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+117,0,"pp25",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+121,0,"pp26",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+125,0,"pp27",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+129,0,"pp28",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+133,0,"pp29",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+137,0,"pp30",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+141,0,"pp31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+145,0,"pp32",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+149,0,"pp33",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+153,0,"pp34",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+157,0,"pp35",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+161,0,"pp36",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+165,0,"pp37",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+169,0,"pp38",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+173,0,"pp39",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+177,0,"pp40",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+181,0,"pp41",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+185,0,"pp42",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+189,0,"pp43",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+193,0,"pp44",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+197,0,"pp45",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+201,0,"pp46",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+205,0,"pp47",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+209,0,"pp48",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+213,0,"pp49",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+217,0,"pp50",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+221,0,"pp51",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+225,0,"pp52",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+229,0,"pp53",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+233,0,"pp54",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+237,0,"pp55",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+241,0,"pp56",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+245,0,"pp57",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+249,0,"pp58",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+253,0,"pp59",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+257,0,"pp60",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+261,0,"pp61",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+265,0,"pp62",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+269,0,"pp63",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+273,0,"l0_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+277,0,"l0_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+281,0,"l0_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+285,0,"l0_3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+289,0,"l0_4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+293,0,"l0_5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+297,0,"l0_6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+301,0,"l0_7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+305,0,"l0_8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+309,0,"l0_9",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+313,0,"l0_10",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+317,0,"l0_11",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+321,0,"l0_12",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+325,0,"l0_13",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+329,0,"l0_14",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+333,0,"l0_15",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+337,0,"l0_16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+341,0,"l0_17",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+345,0,"l0_18",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+349,0,"l0_19",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+353,0,"l0_20",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+357,0,"l0_21",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+361,0,"l0_22",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+365,0,"l0_23",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+369,0,"l0_24",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+373,0,"l0_25",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+377,0,"l0_26",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+381,0,"l0_27",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+385,0,"l0_28",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+389,0,"l0_29",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+393,0,"l0_30",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+397,0,"l0_31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+401,0,"l1_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+405,0,"l1_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+409,0,"l1_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+413,0,"l1_3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+417,0,"l1_4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+421,0,"l1_5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+425,0,"l1_6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+429,0,"l1_7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+433,0,"l1_8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+437,0,"l1_9",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+441,0,"l1_10",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+445,0,"l1_11",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+449,0,"l1_12",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+453,0,"l1_13",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+457,0,"l1_14",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+461,0,"l1_15",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+465,0,"l2_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+469,0,"l2_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+473,0,"l2_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+477,0,"l2_3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+481,0,"l2_4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+485,0,"l2_5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+489,0,"l2_6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+493,0,"l2_7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+497,0,"l3_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+501,0,"l3_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+505,0,"l3_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+509,0,"l3_3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+513,0,"l4_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+517,0,"l4_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+521,0,"l5_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->pushPrefix("A0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+525,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+529,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+533,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+537,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+541,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+545,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+549,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+553,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+557,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+561,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+565,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+569,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A12", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+573,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+577,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+581,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A13", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+585,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+589,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+593,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A14", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+597,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+601,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+605,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A15", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+609,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+613,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+617,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A16", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+621,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+625,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+629,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A17", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+633,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+637,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+641,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A18", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+645,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+649,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+653,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A19", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+657,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+661,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+665,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+669,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+673,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+677,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A20", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+681,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+685,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+689,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A21", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+693,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+697,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+701,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A22", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+705,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+709,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+713,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A23", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+717,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+721,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+725,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A24", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+729,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+733,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+737,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A25", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+741,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+745,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+749,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A26", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+753,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+757,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+761,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A27", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+765,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+769,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+773,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A28", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+777,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+781,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+785,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A29", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+789,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+793,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+797,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+801,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+805,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+809,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A30", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+813,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+817,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+821,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A31", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+825,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+829,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+833,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A32", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+837,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+841,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+845,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A33", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+849,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+853,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+857,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A34", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+861,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+865,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+869,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A35", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+873,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+877,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+881,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A36", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+885,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+889,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+893,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A37", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+897,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+901,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+905,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A38", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+909,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+913,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+917,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A39", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+921,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+925,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+929,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+933,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+937,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+941,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A40", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+945,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+949,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+953,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A41", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+957,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+961,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+965,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A42", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+969,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+973,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+977,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A43", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+981,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+985,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+989,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A44", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+993,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+997,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1001,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A45", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1005,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1009,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1013,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A46", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1017,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1021,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1025,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A47", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1029,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1033,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1037,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A48", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1041,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1045,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1049,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A49", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1053,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1057,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1061,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A5", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1065,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1069,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1073,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A50", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1077,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1081,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1085,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A51", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1089,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1093,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1097,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A52", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1101,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1105,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1109,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A53", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1113,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1117,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1121,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A54", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1125,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1129,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1133,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A55", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1137,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1141,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1145,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A56", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1149,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1153,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1157,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A57", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1161,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1165,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1169,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A58", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1173,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1177,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1181,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A59", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1185,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1189,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1193,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A6", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1197,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1201,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1205,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A60", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1209,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1213,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1217,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A61", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1221,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1225,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1229,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A62", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1233,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1237,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1241,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A7", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1245,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1249,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1253,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1257,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1261,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1265,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->pushPrefix("A9", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declArray(c+1269,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1273,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declArray(c+1277,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullQData(oldp+1,(vlSelfRef.a),64);
    bufp->fullQData(oldp+3,(vlSelfRef.b),64);
    bufp->fullWData(oldp+5,(vlSelfRef.product),128);
    bufp->fullQData(oldp+9,(vlSelfRef.multiplier__DOT__a),64);
    bufp->fullQData(oldp+11,(vlSelfRef.multiplier__DOT__b),64);
    bufp->fullWData(oldp+13,(vlSelfRef.multiplier__DOT__product),128);
    bufp->fullWData(oldp+17,(vlSelfRef.multiplier__DOT__pp0),128);
    bufp->fullWData(oldp+21,(vlSelfRef.multiplier__DOT__pp1),128);
    bufp->fullWData(oldp+25,(vlSelfRef.multiplier__DOT__pp2),128);
    bufp->fullWData(oldp+29,(vlSelfRef.multiplier__DOT__pp3),128);
    bufp->fullWData(oldp+33,(vlSelfRef.multiplier__DOT__pp4),128);
    bufp->fullWData(oldp+37,(vlSelfRef.multiplier__DOT__pp5),128);
    bufp->fullWData(oldp+41,(vlSelfRef.multiplier__DOT__pp6),128);
    bufp->fullWData(oldp+45,(vlSelfRef.multiplier__DOT__pp7),128);
    bufp->fullWData(oldp+49,(vlSelfRef.multiplier__DOT__pp8),128);
    bufp->fullWData(oldp+53,(vlSelfRef.multiplier__DOT__pp9),128);
    bufp->fullWData(oldp+57,(vlSelfRef.multiplier__DOT__pp10),128);
    bufp->fullWData(oldp+61,(vlSelfRef.multiplier__DOT__pp11),128);
    bufp->fullWData(oldp+65,(vlSelfRef.multiplier__DOT__pp12),128);
    bufp->fullWData(oldp+69,(vlSelfRef.multiplier__DOT__pp13),128);
    bufp->fullWData(oldp+73,(vlSelfRef.multiplier__DOT__pp14),128);
    bufp->fullWData(oldp+77,(vlSelfRef.multiplier__DOT__pp15),128);
    bufp->fullWData(oldp+81,(vlSelfRef.multiplier__DOT__pp16),128);
    bufp->fullWData(oldp+85,(vlSelfRef.multiplier__DOT__pp17),128);
    bufp->fullWData(oldp+89,(vlSelfRef.multiplier__DOT__pp18),128);
    bufp->fullWData(oldp+93,(vlSelfRef.multiplier__DOT__pp19),128);
    bufp->fullWData(oldp+97,(vlSelfRef.multiplier__DOT__pp20),128);
    bufp->fullWData(oldp+101,(vlSelfRef.multiplier__DOT__pp21),128);
    bufp->fullWData(oldp+105,(vlSelfRef.multiplier__DOT__pp22),128);
    bufp->fullWData(oldp+109,(vlSelfRef.multiplier__DOT__pp23),128);
    bufp->fullWData(oldp+113,(vlSelfRef.multiplier__DOT__pp24),128);
    bufp->fullWData(oldp+117,(vlSelfRef.multiplier__DOT__pp25),128);
    bufp->fullWData(oldp+121,(vlSelfRef.multiplier__DOT__pp26),128);
    bufp->fullWData(oldp+125,(vlSelfRef.multiplier__DOT__pp27),128);
    bufp->fullWData(oldp+129,(vlSelfRef.multiplier__DOT__pp28),128);
    bufp->fullWData(oldp+133,(vlSelfRef.multiplier__DOT__pp29),128);
    bufp->fullWData(oldp+137,(vlSelfRef.multiplier__DOT__pp30),128);
    bufp->fullWData(oldp+141,(vlSelfRef.multiplier__DOT__pp31),128);
    bufp->fullWData(oldp+145,(vlSelfRef.multiplier__DOT__pp32),128);
    bufp->fullWData(oldp+149,(vlSelfRef.multiplier__DOT__pp33),128);
    bufp->fullWData(oldp+153,(vlSelfRef.multiplier__DOT__pp34),128);
    bufp->fullWData(oldp+157,(vlSelfRef.multiplier__DOT__pp35),128);
    bufp->fullWData(oldp+161,(vlSelfRef.multiplier__DOT__pp36),128);
    bufp->fullWData(oldp+165,(vlSelfRef.multiplier__DOT__pp37),128);
    bufp->fullWData(oldp+169,(vlSelfRef.multiplier__DOT__pp38),128);
    bufp->fullWData(oldp+173,(vlSelfRef.multiplier__DOT__pp39),128);
    bufp->fullWData(oldp+177,(vlSelfRef.multiplier__DOT__pp40),128);
    bufp->fullWData(oldp+181,(vlSelfRef.multiplier__DOT__pp41),128);
    bufp->fullWData(oldp+185,(vlSelfRef.multiplier__DOT__pp42),128);
    bufp->fullWData(oldp+189,(vlSelfRef.multiplier__DOT__pp43),128);
    bufp->fullWData(oldp+193,(vlSelfRef.multiplier__DOT__pp44),128);
    bufp->fullWData(oldp+197,(vlSelfRef.multiplier__DOT__pp45),128);
    bufp->fullWData(oldp+201,(vlSelfRef.multiplier__DOT__pp46),128);
    bufp->fullWData(oldp+205,(vlSelfRef.multiplier__DOT__pp47),128);
    bufp->fullWData(oldp+209,(vlSelfRef.multiplier__DOT__pp48),128);
    bufp->fullWData(oldp+213,(vlSelfRef.multiplier__DOT__pp49),128);
    bufp->fullWData(oldp+217,(vlSelfRef.multiplier__DOT__pp50),128);
    bufp->fullWData(oldp+221,(vlSelfRef.multiplier__DOT__pp51),128);
    bufp->fullWData(oldp+225,(vlSelfRef.multiplier__DOT__pp52),128);
    bufp->fullWData(oldp+229,(vlSelfRef.multiplier__DOT__pp53),128);
    bufp->fullWData(oldp+233,(vlSelfRef.multiplier__DOT__pp54),128);
    bufp->fullWData(oldp+237,(vlSelfRef.multiplier__DOT__pp55),128);
    bufp->fullWData(oldp+241,(vlSelfRef.multiplier__DOT__pp56),128);
    bufp->fullWData(oldp+245,(vlSelfRef.multiplier__DOT__pp57),128);
    bufp->fullWData(oldp+249,(vlSelfRef.multiplier__DOT__pp58),128);
    bufp->fullWData(oldp+253,(vlSelfRef.multiplier__DOT__pp59),128);
    bufp->fullWData(oldp+257,(vlSelfRef.multiplier__DOT__pp60),128);
    bufp->fullWData(oldp+261,(vlSelfRef.multiplier__DOT__pp61),128);
    bufp->fullWData(oldp+265,(vlSelfRef.multiplier__DOT__pp62),128);
    bufp->fullWData(oldp+269,(vlSelfRef.multiplier__DOT__pp63),128);
    bufp->fullWData(oldp+273,(vlSelfRef.multiplier__DOT__l0_0),128);
    bufp->fullWData(oldp+277,(vlSelfRef.multiplier__DOT__l0_1),128);
    bufp->fullWData(oldp+281,(vlSelfRef.multiplier__DOT__l0_2),128);
    bufp->fullWData(oldp+285,(vlSelfRef.multiplier__DOT__l0_3),128);
    bufp->fullWData(oldp+289,(vlSelfRef.multiplier__DOT__l0_4),128);
    bufp->fullWData(oldp+293,(vlSelfRef.multiplier__DOT__l0_5),128);
    bufp->fullWData(oldp+297,(vlSelfRef.multiplier__DOT__l0_6),128);
    bufp->fullWData(oldp+301,(vlSelfRef.multiplier__DOT__l0_7),128);
    bufp->fullWData(oldp+305,(vlSelfRef.multiplier__DOT__l0_8),128);
    bufp->fullWData(oldp+309,(vlSelfRef.multiplier__DOT__l0_9),128);
    bufp->fullWData(oldp+313,(vlSelfRef.multiplier__DOT__l0_10),128);
    bufp->fullWData(oldp+317,(vlSelfRef.multiplier__DOT__l0_11),128);
    bufp->fullWData(oldp+321,(vlSelfRef.multiplier__DOT__l0_12),128);
    bufp->fullWData(oldp+325,(vlSelfRef.multiplier__DOT__l0_13),128);
    bufp->fullWData(oldp+329,(vlSelfRef.multiplier__DOT__l0_14),128);
    bufp->fullWData(oldp+333,(vlSelfRef.multiplier__DOT__l0_15),128);
    bufp->fullWData(oldp+337,(vlSelfRef.multiplier__DOT__l0_16),128);
    bufp->fullWData(oldp+341,(vlSelfRef.multiplier__DOT__l0_17),128);
    bufp->fullWData(oldp+345,(vlSelfRef.multiplier__DOT__l0_18),128);
    bufp->fullWData(oldp+349,(vlSelfRef.multiplier__DOT__l0_19),128);
    bufp->fullWData(oldp+353,(vlSelfRef.multiplier__DOT__l0_20),128);
    bufp->fullWData(oldp+357,(vlSelfRef.multiplier__DOT__l0_21),128);
    bufp->fullWData(oldp+361,(vlSelfRef.multiplier__DOT__l0_22),128);
    bufp->fullWData(oldp+365,(vlSelfRef.multiplier__DOT__l0_23),128);
    bufp->fullWData(oldp+369,(vlSelfRef.multiplier__DOT__l0_24),128);
    bufp->fullWData(oldp+373,(vlSelfRef.multiplier__DOT__l0_25),128);
    bufp->fullWData(oldp+377,(vlSelfRef.multiplier__DOT__l0_26),128);
    bufp->fullWData(oldp+381,(vlSelfRef.multiplier__DOT__l0_27),128);
    bufp->fullWData(oldp+385,(vlSelfRef.multiplier__DOT__l0_28),128);
    bufp->fullWData(oldp+389,(vlSelfRef.multiplier__DOT__l0_29),128);
    bufp->fullWData(oldp+393,(vlSelfRef.multiplier__DOT__l0_30),128);
    bufp->fullWData(oldp+397,(vlSelfRef.multiplier__DOT__l0_31),128);
    bufp->fullWData(oldp+401,(vlSelfRef.multiplier__DOT__l1_0),128);
    bufp->fullWData(oldp+405,(vlSelfRef.multiplier__DOT__l1_1),128);
    bufp->fullWData(oldp+409,(vlSelfRef.multiplier__DOT__l1_2),128);
    bufp->fullWData(oldp+413,(vlSelfRef.multiplier__DOT__l1_3),128);
    bufp->fullWData(oldp+417,(vlSelfRef.multiplier__DOT__l1_4),128);
    bufp->fullWData(oldp+421,(vlSelfRef.multiplier__DOT__l1_5),128);
    bufp->fullWData(oldp+425,(vlSelfRef.multiplier__DOT__l1_6),128);
    bufp->fullWData(oldp+429,(vlSelfRef.multiplier__DOT__l1_7),128);
    bufp->fullWData(oldp+433,(vlSelfRef.multiplier__DOT__l1_8),128);
    bufp->fullWData(oldp+437,(vlSelfRef.multiplier__DOT__l1_9),128);
    bufp->fullWData(oldp+441,(vlSelfRef.multiplier__DOT__l1_10),128);
    bufp->fullWData(oldp+445,(vlSelfRef.multiplier__DOT__l1_11),128);
    bufp->fullWData(oldp+449,(vlSelfRef.multiplier__DOT__l1_12),128);
    bufp->fullWData(oldp+453,(vlSelfRef.multiplier__DOT__l1_13),128);
    bufp->fullWData(oldp+457,(vlSelfRef.multiplier__DOT__l1_14),128);
    bufp->fullWData(oldp+461,(vlSelfRef.multiplier__DOT__l1_15),128);
    bufp->fullWData(oldp+465,(vlSelfRef.multiplier__DOT__l2_0),128);
    bufp->fullWData(oldp+469,(vlSelfRef.multiplier__DOT__l2_1),128);
    bufp->fullWData(oldp+473,(vlSelfRef.multiplier__DOT__l2_2),128);
    bufp->fullWData(oldp+477,(vlSelfRef.multiplier__DOT__l2_3),128);
    bufp->fullWData(oldp+481,(vlSelfRef.multiplier__DOT__l2_4),128);
    bufp->fullWData(oldp+485,(vlSelfRef.multiplier__DOT__l2_5),128);
    bufp->fullWData(oldp+489,(vlSelfRef.multiplier__DOT__l2_6),128);
    bufp->fullWData(oldp+493,(vlSelfRef.multiplier__DOT__l2_7),128);
    bufp->fullWData(oldp+497,(vlSelfRef.multiplier__DOT__l3_0),128);
    bufp->fullWData(oldp+501,(vlSelfRef.multiplier__DOT__l3_1),128);
    bufp->fullWData(oldp+505,(vlSelfRef.multiplier__DOT__l3_2),128);
    bufp->fullWData(oldp+509,(vlSelfRef.multiplier__DOT__l3_3),128);
    bufp->fullWData(oldp+513,(vlSelfRef.multiplier__DOT__l4_0),128);
    bufp->fullWData(oldp+517,(vlSelfRef.multiplier__DOT__l4_1),128);
    bufp->fullWData(oldp+521,(vlSelfRef.multiplier__DOT__l5_0),128);
    bufp->fullWData(oldp+525,(vlSelfRef.multiplier__DOT__A0__DOT__a),128);
    bufp->fullWData(oldp+529,(vlSelfRef.multiplier__DOT__A0__DOT__b),128);
    bufp->fullWData(oldp+533,(vlSelfRef.multiplier__DOT__A0__DOT__sum),128);
    bufp->fullWData(oldp+537,(vlSelfRef.multiplier__DOT__A1__DOT__a),128);
    bufp->fullWData(oldp+541,(vlSelfRef.multiplier__DOT__A1__DOT__b),128);
    bufp->fullWData(oldp+545,(vlSelfRef.multiplier__DOT__A1__DOT__sum),128);
    bufp->fullWData(oldp+549,(vlSelfRef.multiplier__DOT__A10__DOT__a),128);
    bufp->fullWData(oldp+553,(vlSelfRef.multiplier__DOT__A10__DOT__b),128);
    bufp->fullWData(oldp+557,(vlSelfRef.multiplier__DOT__A10__DOT__sum),128);
    bufp->fullWData(oldp+561,(vlSelfRef.multiplier__DOT__A11__DOT__a),128);
    bufp->fullWData(oldp+565,(vlSelfRef.multiplier__DOT__A11__DOT__b),128);
    bufp->fullWData(oldp+569,(vlSelfRef.multiplier__DOT__A11__DOT__sum),128);
    bufp->fullWData(oldp+573,(vlSelfRef.multiplier__DOT__A12__DOT__a),128);
    bufp->fullWData(oldp+577,(vlSelfRef.multiplier__DOT__A12__DOT__b),128);
    bufp->fullWData(oldp+581,(vlSelfRef.multiplier__DOT__A12__DOT__sum),128);
    bufp->fullWData(oldp+585,(vlSelfRef.multiplier__DOT__A13__DOT__a),128);
    bufp->fullWData(oldp+589,(vlSelfRef.multiplier__DOT__A13__DOT__b),128);
    bufp->fullWData(oldp+593,(vlSelfRef.multiplier__DOT__A13__DOT__sum),128);
    bufp->fullWData(oldp+597,(vlSelfRef.multiplier__DOT__A14__DOT__a),128);
    bufp->fullWData(oldp+601,(vlSelfRef.multiplier__DOT__A14__DOT__b),128);
    bufp->fullWData(oldp+605,(vlSelfRef.multiplier__DOT__A14__DOT__sum),128);
    bufp->fullWData(oldp+609,(vlSelfRef.multiplier__DOT__A15__DOT__a),128);
    bufp->fullWData(oldp+613,(vlSelfRef.multiplier__DOT__A15__DOT__b),128);
    bufp->fullWData(oldp+617,(vlSelfRef.multiplier__DOT__A15__DOT__sum),128);
    bufp->fullWData(oldp+621,(vlSelfRef.multiplier__DOT__A16__DOT__a),128);
    bufp->fullWData(oldp+625,(vlSelfRef.multiplier__DOT__A16__DOT__b),128);
    bufp->fullWData(oldp+629,(vlSelfRef.multiplier__DOT__A16__DOT__sum),128);
    bufp->fullWData(oldp+633,(vlSelfRef.multiplier__DOT__A17__DOT__a),128);
    bufp->fullWData(oldp+637,(vlSelfRef.multiplier__DOT__A17__DOT__b),128);
    bufp->fullWData(oldp+641,(vlSelfRef.multiplier__DOT__A17__DOT__sum),128);
    bufp->fullWData(oldp+645,(vlSelfRef.multiplier__DOT__A18__DOT__a),128);
    bufp->fullWData(oldp+649,(vlSelfRef.multiplier__DOT__A18__DOT__b),128);
    bufp->fullWData(oldp+653,(vlSelfRef.multiplier__DOT__A18__DOT__sum),128);
    bufp->fullWData(oldp+657,(vlSelfRef.multiplier__DOT__A19__DOT__a),128);
    bufp->fullWData(oldp+661,(vlSelfRef.multiplier__DOT__A19__DOT__b),128);
    bufp->fullWData(oldp+665,(vlSelfRef.multiplier__DOT__A19__DOT__sum),128);
    bufp->fullWData(oldp+669,(vlSelfRef.multiplier__DOT__A2__DOT__a),128);
    bufp->fullWData(oldp+673,(vlSelfRef.multiplier__DOT__A2__DOT__b),128);
    bufp->fullWData(oldp+677,(vlSelfRef.multiplier__DOT__A2__DOT__sum),128);
    bufp->fullWData(oldp+681,(vlSelfRef.multiplier__DOT__A20__DOT__a),128);
    bufp->fullWData(oldp+685,(vlSelfRef.multiplier__DOT__A20__DOT__b),128);
    bufp->fullWData(oldp+689,(vlSelfRef.multiplier__DOT__A20__DOT__sum),128);
    bufp->fullWData(oldp+693,(vlSelfRef.multiplier__DOT__A21__DOT__a),128);
    bufp->fullWData(oldp+697,(vlSelfRef.multiplier__DOT__A21__DOT__b),128);
    bufp->fullWData(oldp+701,(vlSelfRef.multiplier__DOT__A21__DOT__sum),128);
    bufp->fullWData(oldp+705,(vlSelfRef.multiplier__DOT__A22__DOT__a),128);
    bufp->fullWData(oldp+709,(vlSelfRef.multiplier__DOT__A22__DOT__b),128);
    bufp->fullWData(oldp+713,(vlSelfRef.multiplier__DOT__A22__DOT__sum),128);
    bufp->fullWData(oldp+717,(vlSelfRef.multiplier__DOT__A23__DOT__a),128);
    bufp->fullWData(oldp+721,(vlSelfRef.multiplier__DOT__A23__DOT__b),128);
    bufp->fullWData(oldp+725,(vlSelfRef.multiplier__DOT__A23__DOT__sum),128);
    bufp->fullWData(oldp+729,(vlSelfRef.multiplier__DOT__A24__DOT__a),128);
    bufp->fullWData(oldp+733,(vlSelfRef.multiplier__DOT__A24__DOT__b),128);
    bufp->fullWData(oldp+737,(vlSelfRef.multiplier__DOT__A24__DOT__sum),128);
    bufp->fullWData(oldp+741,(vlSelfRef.multiplier__DOT__A25__DOT__a),128);
    bufp->fullWData(oldp+745,(vlSelfRef.multiplier__DOT__A25__DOT__b),128);
    bufp->fullWData(oldp+749,(vlSelfRef.multiplier__DOT__A25__DOT__sum),128);
    bufp->fullWData(oldp+753,(vlSelfRef.multiplier__DOT__A26__DOT__a),128);
    bufp->fullWData(oldp+757,(vlSelfRef.multiplier__DOT__A26__DOT__b),128);
    bufp->fullWData(oldp+761,(vlSelfRef.multiplier__DOT__A26__DOT__sum),128);
    bufp->fullWData(oldp+765,(vlSelfRef.multiplier__DOT__A27__DOT__a),128);
    bufp->fullWData(oldp+769,(vlSelfRef.multiplier__DOT__A27__DOT__b),128);
    bufp->fullWData(oldp+773,(vlSelfRef.multiplier__DOT__A27__DOT__sum),128);
    bufp->fullWData(oldp+777,(vlSelfRef.multiplier__DOT__A28__DOT__a),128);
    bufp->fullWData(oldp+781,(vlSelfRef.multiplier__DOT__A28__DOT__b),128);
    bufp->fullWData(oldp+785,(vlSelfRef.multiplier__DOT__A28__DOT__sum),128);
    bufp->fullWData(oldp+789,(vlSelfRef.multiplier__DOT__A29__DOT__a),128);
    bufp->fullWData(oldp+793,(vlSelfRef.multiplier__DOT__A29__DOT__b),128);
    bufp->fullWData(oldp+797,(vlSelfRef.multiplier__DOT__A29__DOT__sum),128);
    bufp->fullWData(oldp+801,(vlSelfRef.multiplier__DOT__A3__DOT__a),128);
    bufp->fullWData(oldp+805,(vlSelfRef.multiplier__DOT__A3__DOT__b),128);
    bufp->fullWData(oldp+809,(vlSelfRef.multiplier__DOT__A3__DOT__sum),128);
    bufp->fullWData(oldp+813,(vlSelfRef.multiplier__DOT__A30__DOT__a),128);
    bufp->fullWData(oldp+817,(vlSelfRef.multiplier__DOT__A30__DOT__b),128);
    bufp->fullWData(oldp+821,(vlSelfRef.multiplier__DOT__A30__DOT__sum),128);
    bufp->fullWData(oldp+825,(vlSelfRef.multiplier__DOT__A31__DOT__a),128);
    bufp->fullWData(oldp+829,(vlSelfRef.multiplier__DOT__A31__DOT__b),128);
    bufp->fullWData(oldp+833,(vlSelfRef.multiplier__DOT__A31__DOT__sum),128);
    bufp->fullWData(oldp+837,(vlSelfRef.multiplier__DOT__A32__DOT__a),128);
    bufp->fullWData(oldp+841,(vlSelfRef.multiplier__DOT__A32__DOT__b),128);
    bufp->fullWData(oldp+845,(vlSelfRef.multiplier__DOT__A32__DOT__sum),128);
    bufp->fullWData(oldp+849,(vlSelfRef.multiplier__DOT__A33__DOT__a),128);
    bufp->fullWData(oldp+853,(vlSelfRef.multiplier__DOT__A33__DOT__b),128);
    bufp->fullWData(oldp+857,(vlSelfRef.multiplier__DOT__A33__DOT__sum),128);
    bufp->fullWData(oldp+861,(vlSelfRef.multiplier__DOT__A34__DOT__a),128);
    bufp->fullWData(oldp+865,(vlSelfRef.multiplier__DOT__A34__DOT__b),128);
    bufp->fullWData(oldp+869,(vlSelfRef.multiplier__DOT__A34__DOT__sum),128);
    bufp->fullWData(oldp+873,(vlSelfRef.multiplier__DOT__A35__DOT__a),128);
    bufp->fullWData(oldp+877,(vlSelfRef.multiplier__DOT__A35__DOT__b),128);
    bufp->fullWData(oldp+881,(vlSelfRef.multiplier__DOT__A35__DOT__sum),128);
    bufp->fullWData(oldp+885,(vlSelfRef.multiplier__DOT__A36__DOT__a),128);
    bufp->fullWData(oldp+889,(vlSelfRef.multiplier__DOT__A36__DOT__b),128);
    bufp->fullWData(oldp+893,(vlSelfRef.multiplier__DOT__A36__DOT__sum),128);
    bufp->fullWData(oldp+897,(vlSelfRef.multiplier__DOT__A37__DOT__a),128);
    bufp->fullWData(oldp+901,(vlSelfRef.multiplier__DOT__A37__DOT__b),128);
    bufp->fullWData(oldp+905,(vlSelfRef.multiplier__DOT__A37__DOT__sum),128);
    bufp->fullWData(oldp+909,(vlSelfRef.multiplier__DOT__A38__DOT__a),128);
    bufp->fullWData(oldp+913,(vlSelfRef.multiplier__DOT__A38__DOT__b),128);
    bufp->fullWData(oldp+917,(vlSelfRef.multiplier__DOT__A38__DOT__sum),128);
    bufp->fullWData(oldp+921,(vlSelfRef.multiplier__DOT__A39__DOT__a),128);
    bufp->fullWData(oldp+925,(vlSelfRef.multiplier__DOT__A39__DOT__b),128);
    bufp->fullWData(oldp+929,(vlSelfRef.multiplier__DOT__A39__DOT__sum),128);
    bufp->fullWData(oldp+933,(vlSelfRef.multiplier__DOT__A4__DOT__a),128);
    bufp->fullWData(oldp+937,(vlSelfRef.multiplier__DOT__A4__DOT__b),128);
    bufp->fullWData(oldp+941,(vlSelfRef.multiplier__DOT__A4__DOT__sum),128);
    bufp->fullWData(oldp+945,(vlSelfRef.multiplier__DOT__A40__DOT__a),128);
    bufp->fullWData(oldp+949,(vlSelfRef.multiplier__DOT__A40__DOT__b),128);
    bufp->fullWData(oldp+953,(vlSelfRef.multiplier__DOT__A40__DOT__sum),128);
    bufp->fullWData(oldp+957,(vlSelfRef.multiplier__DOT__A41__DOT__a),128);
    bufp->fullWData(oldp+961,(vlSelfRef.multiplier__DOT__A41__DOT__b),128);
    bufp->fullWData(oldp+965,(vlSelfRef.multiplier__DOT__A41__DOT__sum),128);
    bufp->fullWData(oldp+969,(vlSelfRef.multiplier__DOT__A42__DOT__a),128);
    bufp->fullWData(oldp+973,(vlSelfRef.multiplier__DOT__A42__DOT__b),128);
    bufp->fullWData(oldp+977,(vlSelfRef.multiplier__DOT__A42__DOT__sum),128);
    bufp->fullWData(oldp+981,(vlSelfRef.multiplier__DOT__A43__DOT__a),128);
    bufp->fullWData(oldp+985,(vlSelfRef.multiplier__DOT__A43__DOT__b),128);
    bufp->fullWData(oldp+989,(vlSelfRef.multiplier__DOT__A43__DOT__sum),128);
    bufp->fullWData(oldp+993,(vlSelfRef.multiplier__DOT__A44__DOT__a),128);
    bufp->fullWData(oldp+997,(vlSelfRef.multiplier__DOT__A44__DOT__b),128);
    bufp->fullWData(oldp+1001,(vlSelfRef.multiplier__DOT__A44__DOT__sum),128);
    bufp->fullWData(oldp+1005,(vlSelfRef.multiplier__DOT__A45__DOT__a),128);
    bufp->fullWData(oldp+1009,(vlSelfRef.multiplier__DOT__A45__DOT__b),128);
    bufp->fullWData(oldp+1013,(vlSelfRef.multiplier__DOT__A45__DOT__sum),128);
    bufp->fullWData(oldp+1017,(vlSelfRef.multiplier__DOT__A46__DOT__a),128);
    bufp->fullWData(oldp+1021,(vlSelfRef.multiplier__DOT__A46__DOT__b),128);
    bufp->fullWData(oldp+1025,(vlSelfRef.multiplier__DOT__A46__DOT__sum),128);
    bufp->fullWData(oldp+1029,(vlSelfRef.multiplier__DOT__A47__DOT__a),128);
    bufp->fullWData(oldp+1033,(vlSelfRef.multiplier__DOT__A47__DOT__b),128);
    bufp->fullWData(oldp+1037,(vlSelfRef.multiplier__DOT__A47__DOT__sum),128);
    bufp->fullWData(oldp+1041,(vlSelfRef.multiplier__DOT__A48__DOT__a),128);
    bufp->fullWData(oldp+1045,(vlSelfRef.multiplier__DOT__A48__DOT__b),128);
    bufp->fullWData(oldp+1049,(vlSelfRef.multiplier__DOT__A48__DOT__sum),128);
    bufp->fullWData(oldp+1053,(vlSelfRef.multiplier__DOT__A49__DOT__a),128);
    bufp->fullWData(oldp+1057,(vlSelfRef.multiplier__DOT__A49__DOT__b),128);
    bufp->fullWData(oldp+1061,(vlSelfRef.multiplier__DOT__A49__DOT__sum),128);
    bufp->fullWData(oldp+1065,(vlSelfRef.multiplier__DOT__A5__DOT__a),128);
    bufp->fullWData(oldp+1069,(vlSelfRef.multiplier__DOT__A5__DOT__b),128);
    bufp->fullWData(oldp+1073,(vlSelfRef.multiplier__DOT__A5__DOT__sum),128);
    bufp->fullWData(oldp+1077,(vlSelfRef.multiplier__DOT__A50__DOT__a),128);
    bufp->fullWData(oldp+1081,(vlSelfRef.multiplier__DOT__A50__DOT__b),128);
    bufp->fullWData(oldp+1085,(vlSelfRef.multiplier__DOT__A50__DOT__sum),128);
    bufp->fullWData(oldp+1089,(vlSelfRef.multiplier__DOT__A51__DOT__a),128);
    bufp->fullWData(oldp+1093,(vlSelfRef.multiplier__DOT__A51__DOT__b),128);
    bufp->fullWData(oldp+1097,(vlSelfRef.multiplier__DOT__A51__DOT__sum),128);
    bufp->fullWData(oldp+1101,(vlSelfRef.multiplier__DOT__A52__DOT__a),128);
    bufp->fullWData(oldp+1105,(vlSelfRef.multiplier__DOT__A52__DOT__b),128);
    bufp->fullWData(oldp+1109,(vlSelfRef.multiplier__DOT__A52__DOT__sum),128);
    bufp->fullWData(oldp+1113,(vlSelfRef.multiplier__DOT__A53__DOT__a),128);
    bufp->fullWData(oldp+1117,(vlSelfRef.multiplier__DOT__A53__DOT__b),128);
    bufp->fullWData(oldp+1121,(vlSelfRef.multiplier__DOT__A53__DOT__sum),128);
    bufp->fullWData(oldp+1125,(vlSelfRef.multiplier__DOT__A54__DOT__a),128);
    bufp->fullWData(oldp+1129,(vlSelfRef.multiplier__DOT__A54__DOT__b),128);
    bufp->fullWData(oldp+1133,(vlSelfRef.multiplier__DOT__A54__DOT__sum),128);
    bufp->fullWData(oldp+1137,(vlSelfRef.multiplier__DOT__A55__DOT__a),128);
    bufp->fullWData(oldp+1141,(vlSelfRef.multiplier__DOT__A55__DOT__b),128);
    bufp->fullWData(oldp+1145,(vlSelfRef.multiplier__DOT__A55__DOT__sum),128);
    bufp->fullWData(oldp+1149,(vlSelfRef.multiplier__DOT__A56__DOT__a),128);
    bufp->fullWData(oldp+1153,(vlSelfRef.multiplier__DOT__A56__DOT__b),128);
    bufp->fullWData(oldp+1157,(vlSelfRef.multiplier__DOT__A56__DOT__sum),128);
    bufp->fullWData(oldp+1161,(vlSelfRef.multiplier__DOT__A57__DOT__a),128);
    bufp->fullWData(oldp+1165,(vlSelfRef.multiplier__DOT__A57__DOT__b),128);
    bufp->fullWData(oldp+1169,(vlSelfRef.multiplier__DOT__A57__DOT__sum),128);
    bufp->fullWData(oldp+1173,(vlSelfRef.multiplier__DOT__A58__DOT__a),128);
    bufp->fullWData(oldp+1177,(vlSelfRef.multiplier__DOT__A58__DOT__b),128);
    bufp->fullWData(oldp+1181,(vlSelfRef.multiplier__DOT__A58__DOT__sum),128);
    bufp->fullWData(oldp+1185,(vlSelfRef.multiplier__DOT__A59__DOT__a),128);
    bufp->fullWData(oldp+1189,(vlSelfRef.multiplier__DOT__A59__DOT__b),128);
    bufp->fullWData(oldp+1193,(vlSelfRef.multiplier__DOT__A59__DOT__sum),128);
    bufp->fullWData(oldp+1197,(vlSelfRef.multiplier__DOT__A6__DOT__a),128);
    bufp->fullWData(oldp+1201,(vlSelfRef.multiplier__DOT__A6__DOT__b),128);
    bufp->fullWData(oldp+1205,(vlSelfRef.multiplier__DOT__A6__DOT__sum),128);
    bufp->fullWData(oldp+1209,(vlSelfRef.multiplier__DOT__A60__DOT__a),128);
    bufp->fullWData(oldp+1213,(vlSelfRef.multiplier__DOT__A60__DOT__b),128);
    bufp->fullWData(oldp+1217,(vlSelfRef.multiplier__DOT__A60__DOT__sum),128);
    bufp->fullWData(oldp+1221,(vlSelfRef.multiplier__DOT__A61__DOT__a),128);
    bufp->fullWData(oldp+1225,(vlSelfRef.multiplier__DOT__A61__DOT__b),128);
    bufp->fullWData(oldp+1229,(vlSelfRef.multiplier__DOT__A61__DOT__sum),128);
    bufp->fullWData(oldp+1233,(vlSelfRef.multiplier__DOT__A62__DOT__a),128);
    bufp->fullWData(oldp+1237,(vlSelfRef.multiplier__DOT__A62__DOT__b),128);
    bufp->fullWData(oldp+1241,(vlSelfRef.multiplier__DOT__A62__DOT__sum),128);
    bufp->fullWData(oldp+1245,(vlSelfRef.multiplier__DOT__A7__DOT__a),128);
    bufp->fullWData(oldp+1249,(vlSelfRef.multiplier__DOT__A7__DOT__b),128);
    bufp->fullWData(oldp+1253,(vlSelfRef.multiplier__DOT__A7__DOT__sum),128);
    bufp->fullWData(oldp+1257,(vlSelfRef.multiplier__DOT__A8__DOT__a),128);
    bufp->fullWData(oldp+1261,(vlSelfRef.multiplier__DOT__A8__DOT__b),128);
    bufp->fullWData(oldp+1265,(vlSelfRef.multiplier__DOT__A8__DOT__sum),128);
    bufp->fullWData(oldp+1269,(vlSelfRef.multiplier__DOT__A9__DOT__a),128);
    bufp->fullWData(oldp+1273,(vlSelfRef.multiplier__DOT__A9__DOT__b),128);
    bufp->fullWData(oldp+1277,(vlSelfRef.multiplier__DOT__A9__DOT__sum),128);
}
