// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_multiplier);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A0);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A1);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A10);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A11);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A12);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A13);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A14);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A15);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A16);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A17);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A18);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A19);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A2);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A20);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A21);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A22);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A23);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A24);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A25);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A26);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A27);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A28);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A29);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A3);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A30);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A31);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A32);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A33);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A34);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A35);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A36);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A37);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A38);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A39);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A4);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A40);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A41);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A42);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A43);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A44);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A45);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A46);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A47);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A48);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A49);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A5);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A50);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A51);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A52);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A53);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A54);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A55);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A56);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A57);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A58);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A59);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A6);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A60);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A61);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A62);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A7);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A8);
    __Vhier.remove(&__Vscope_multiplier, &__Vscope_multiplier__A9);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(8089);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_multiplier.configure(this, name(), "multiplier", "multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A0.configure(this, name(), "multiplier.A0", "A0", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A1.configure(this, name(), "multiplier.A1", "A1", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A10.configure(this, name(), "multiplier.A10", "A10", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A11.configure(this, name(), "multiplier.A11", "A11", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A12.configure(this, name(), "multiplier.A12", "A12", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A13.configure(this, name(), "multiplier.A13", "A13", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A14.configure(this, name(), "multiplier.A14", "A14", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A15.configure(this, name(), "multiplier.A15", "A15", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A16.configure(this, name(), "multiplier.A16", "A16", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A17.configure(this, name(), "multiplier.A17", "A17", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A18.configure(this, name(), "multiplier.A18", "A18", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A19.configure(this, name(), "multiplier.A19", "A19", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A2.configure(this, name(), "multiplier.A2", "A2", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A20.configure(this, name(), "multiplier.A20", "A20", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A21.configure(this, name(), "multiplier.A21", "A21", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A22.configure(this, name(), "multiplier.A22", "A22", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A23.configure(this, name(), "multiplier.A23", "A23", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A24.configure(this, name(), "multiplier.A24", "A24", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A25.configure(this, name(), "multiplier.A25", "A25", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A26.configure(this, name(), "multiplier.A26", "A26", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A27.configure(this, name(), "multiplier.A27", "A27", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A28.configure(this, name(), "multiplier.A28", "A28", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A29.configure(this, name(), "multiplier.A29", "A29", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A3.configure(this, name(), "multiplier.A3", "A3", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A30.configure(this, name(), "multiplier.A30", "A30", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A31.configure(this, name(), "multiplier.A31", "A31", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A32.configure(this, name(), "multiplier.A32", "A32", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A33.configure(this, name(), "multiplier.A33", "A33", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A34.configure(this, name(), "multiplier.A34", "A34", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A35.configure(this, name(), "multiplier.A35", "A35", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A36.configure(this, name(), "multiplier.A36", "A36", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A37.configure(this, name(), "multiplier.A37", "A37", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A38.configure(this, name(), "multiplier.A38", "A38", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A39.configure(this, name(), "multiplier.A39", "A39", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A4.configure(this, name(), "multiplier.A4", "A4", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A40.configure(this, name(), "multiplier.A40", "A40", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A41.configure(this, name(), "multiplier.A41", "A41", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A42.configure(this, name(), "multiplier.A42", "A42", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A43.configure(this, name(), "multiplier.A43", "A43", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A44.configure(this, name(), "multiplier.A44", "A44", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A45.configure(this, name(), "multiplier.A45", "A45", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A46.configure(this, name(), "multiplier.A46", "A46", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A47.configure(this, name(), "multiplier.A47", "A47", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A48.configure(this, name(), "multiplier.A48", "A48", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A49.configure(this, name(), "multiplier.A49", "A49", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A5.configure(this, name(), "multiplier.A5", "A5", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A50.configure(this, name(), "multiplier.A50", "A50", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A51.configure(this, name(), "multiplier.A51", "A51", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A52.configure(this, name(), "multiplier.A52", "A52", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A53.configure(this, name(), "multiplier.A53", "A53", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A54.configure(this, name(), "multiplier.A54", "A54", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A55.configure(this, name(), "multiplier.A55", "A55", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A56.configure(this, name(), "multiplier.A56", "A56", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A57.configure(this, name(), "multiplier.A57", "A57", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A58.configure(this, name(), "multiplier.A58", "A58", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A59.configure(this, name(), "multiplier.A59", "A59", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A6.configure(this, name(), "multiplier.A6", "A6", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A60.configure(this, name(), "multiplier.A60", "A60", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A61.configure(this, name(), "multiplier.A61", "A61", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A62.configure(this, name(), "multiplier.A62", "A62", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A7.configure(this, name(), "multiplier.A7", "A7", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A8.configure(this, name(), "multiplier.A8", "A8", "adder128", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_multiplier__A9.configure(this, name(), "multiplier.A9", "A9", "adder128", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_multiplier);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A0);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A1);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A10);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A11);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A12);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A13);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A14);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A15);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A16);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A17);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A18);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A19);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A2);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A20);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A21);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A22);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A23);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A24);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A25);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A26);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A27);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A28);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A29);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A3);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A30);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A31);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A32);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A33);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A34);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A35);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A36);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A37);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A38);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A39);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A4);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A40);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A41);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A42);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A43);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A44);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A45);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A46);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A47);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A48);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A49);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A5);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A50);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A51);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A52);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A53);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A54);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A55);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A56);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A57);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A58);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A59);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A6);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A60);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A61);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A62);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A7);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A8);
    __Vhier.add(&__Vscope_multiplier, &__Vscope_multiplier__A9);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"a", &(TOP.a), false, VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"b", &(TOP.b), false, VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"product", &(TOP.product), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_multiplier.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_0", &(TOP.multiplier__DOT__l0_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_1", &(TOP.multiplier__DOT__l0_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_10", &(TOP.multiplier__DOT__l0_10), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_11", &(TOP.multiplier__DOT__l0_11), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_12", &(TOP.multiplier__DOT__l0_12), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_13", &(TOP.multiplier__DOT__l0_13), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_14", &(TOP.multiplier__DOT__l0_14), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_15", &(TOP.multiplier__DOT__l0_15), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_16", &(TOP.multiplier__DOT__l0_16), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_17", &(TOP.multiplier__DOT__l0_17), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_18", &(TOP.multiplier__DOT__l0_18), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_19", &(TOP.multiplier__DOT__l0_19), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_2", &(TOP.multiplier__DOT__l0_2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_20", &(TOP.multiplier__DOT__l0_20), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_21", &(TOP.multiplier__DOT__l0_21), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_22", &(TOP.multiplier__DOT__l0_22), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_23", &(TOP.multiplier__DOT__l0_23), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_24", &(TOP.multiplier__DOT__l0_24), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_25", &(TOP.multiplier__DOT__l0_25), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_26", &(TOP.multiplier__DOT__l0_26), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_27", &(TOP.multiplier__DOT__l0_27), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_28", &(TOP.multiplier__DOT__l0_28), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_29", &(TOP.multiplier__DOT__l0_29), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_3", &(TOP.multiplier__DOT__l0_3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_30", &(TOP.multiplier__DOT__l0_30), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_31", &(TOP.multiplier__DOT__l0_31), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_4", &(TOP.multiplier__DOT__l0_4), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_5", &(TOP.multiplier__DOT__l0_5), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_6", &(TOP.multiplier__DOT__l0_6), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_7", &(TOP.multiplier__DOT__l0_7), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_8", &(TOP.multiplier__DOT__l0_8), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l0_9", &(TOP.multiplier__DOT__l0_9), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_0", &(TOP.multiplier__DOT__l1_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_1", &(TOP.multiplier__DOT__l1_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_10", &(TOP.multiplier__DOT__l1_10), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_11", &(TOP.multiplier__DOT__l1_11), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_12", &(TOP.multiplier__DOT__l1_12), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_13", &(TOP.multiplier__DOT__l1_13), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_14", &(TOP.multiplier__DOT__l1_14), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_15", &(TOP.multiplier__DOT__l1_15), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_2", &(TOP.multiplier__DOT__l1_2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_3", &(TOP.multiplier__DOT__l1_3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_4", &(TOP.multiplier__DOT__l1_4), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_5", &(TOP.multiplier__DOT__l1_5), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_6", &(TOP.multiplier__DOT__l1_6), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_7", &(TOP.multiplier__DOT__l1_7), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_8", &(TOP.multiplier__DOT__l1_8), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l1_9", &(TOP.multiplier__DOT__l1_9), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_0", &(TOP.multiplier__DOT__l2_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_1", &(TOP.multiplier__DOT__l2_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_2", &(TOP.multiplier__DOT__l2_2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_3", &(TOP.multiplier__DOT__l2_3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_4", &(TOP.multiplier__DOT__l2_4), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_5", &(TOP.multiplier__DOT__l2_5), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_6", &(TOP.multiplier__DOT__l2_6), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l2_7", &(TOP.multiplier__DOT__l2_7), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l3_0", &(TOP.multiplier__DOT__l3_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l3_1", &(TOP.multiplier__DOT__l3_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l3_2", &(TOP.multiplier__DOT__l3_2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l3_3", &(TOP.multiplier__DOT__l3_3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l4_0", &(TOP.multiplier__DOT__l4_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l4_1", &(TOP.multiplier__DOT__l4_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"l5_0", &(TOP.multiplier__DOT__l5_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp0", &(TOP.multiplier__DOT__pp0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp1", &(TOP.multiplier__DOT__pp1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp10", &(TOP.multiplier__DOT__pp10), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp11", &(TOP.multiplier__DOT__pp11), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp12", &(TOP.multiplier__DOT__pp12), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp13", &(TOP.multiplier__DOT__pp13), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp14", &(TOP.multiplier__DOT__pp14), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp15", &(TOP.multiplier__DOT__pp15), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp16", &(TOP.multiplier__DOT__pp16), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp17", &(TOP.multiplier__DOT__pp17), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp18", &(TOP.multiplier__DOT__pp18), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp19", &(TOP.multiplier__DOT__pp19), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp2", &(TOP.multiplier__DOT__pp2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp20", &(TOP.multiplier__DOT__pp20), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp21", &(TOP.multiplier__DOT__pp21), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp22", &(TOP.multiplier__DOT__pp22), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp23", &(TOP.multiplier__DOT__pp23), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp24", &(TOP.multiplier__DOT__pp24), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp25", &(TOP.multiplier__DOT__pp25), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp26", &(TOP.multiplier__DOT__pp26), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp27", &(TOP.multiplier__DOT__pp27), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp28", &(TOP.multiplier__DOT__pp28), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp29", &(TOP.multiplier__DOT__pp29), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp3", &(TOP.multiplier__DOT__pp3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp30", &(TOP.multiplier__DOT__pp30), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp31", &(TOP.multiplier__DOT__pp31), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp32", &(TOP.multiplier__DOT__pp32), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp33", &(TOP.multiplier__DOT__pp33), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp34", &(TOP.multiplier__DOT__pp34), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp35", &(TOP.multiplier__DOT__pp35), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp36", &(TOP.multiplier__DOT__pp36), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp37", &(TOP.multiplier__DOT__pp37), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp38", &(TOP.multiplier__DOT__pp38), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp39", &(TOP.multiplier__DOT__pp39), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp4", &(TOP.multiplier__DOT__pp4), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp40", &(TOP.multiplier__DOT__pp40), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp41", &(TOP.multiplier__DOT__pp41), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp42", &(TOP.multiplier__DOT__pp42), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp43", &(TOP.multiplier__DOT__pp43), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp44", &(TOP.multiplier__DOT__pp44), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp45", &(TOP.multiplier__DOT__pp45), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp46", &(TOP.multiplier__DOT__pp46), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp47", &(TOP.multiplier__DOT__pp47), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp48", &(TOP.multiplier__DOT__pp48), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp49", &(TOP.multiplier__DOT__pp49), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp5", &(TOP.multiplier__DOT__pp5), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp50", &(TOP.multiplier__DOT__pp50), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp51", &(TOP.multiplier__DOT__pp51), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp52", &(TOP.multiplier__DOT__pp52), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp53", &(TOP.multiplier__DOT__pp53), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp54", &(TOP.multiplier__DOT__pp54), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp55", &(TOP.multiplier__DOT__pp55), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp56", &(TOP.multiplier__DOT__pp56), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp57", &(TOP.multiplier__DOT__pp57), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp58", &(TOP.multiplier__DOT__pp58), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp59", &(TOP.multiplier__DOT__pp59), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp6", &(TOP.multiplier__DOT__pp6), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp60", &(TOP.multiplier__DOT__pp60), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp61", &(TOP.multiplier__DOT__pp61), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp62", &(TOP.multiplier__DOT__pp62), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp63", &(TOP.multiplier__DOT__pp63), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp7", &(TOP.multiplier__DOT__pp7), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp8", &(TOP.multiplier__DOT__pp8), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"pp9", &(TOP.multiplier__DOT__pp9), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier.varInsert(__Vfinal,"product", &(TOP.multiplier__DOT__product), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A0.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A0__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A0.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A0__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A0.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A0__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A1.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A1__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A1.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A1__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A1.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A1__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A10.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A10__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A10.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A10__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A10.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A10__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A11.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A11__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A11.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A11__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A11.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A11__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A12.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A12__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A12.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A12__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A12.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A12__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A13.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A13__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A13.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A13__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A13.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A13__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A14.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A14__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A14.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A14__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A14.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A14__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A15.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A15__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A15.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A15__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A15.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A15__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A16.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A16__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A16.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A16__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A16.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A16__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A17.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A17__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A17.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A17__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A17.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A17__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A18.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A18__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A18.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A18__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A18.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A18__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A19.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A19__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A19.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A19__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A19.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A19__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A2.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A2__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A2.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A2__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A2.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A2__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A20.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A20__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A20.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A20__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A20.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A20__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A21.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A21__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A21.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A21__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A21.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A21__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A22.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A22__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A22.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A22__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A22.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A22__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A23.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A23__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A23.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A23__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A23.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A23__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A24.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A24__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A24.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A24__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A24.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A24__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A25.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A25__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A25.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A25__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A25.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A25__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A26.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A26__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A26.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A26__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A26.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A26__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A27.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A27__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A27.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A27__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A27.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A27__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A28.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A28__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A28.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A28__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A28.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A28__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A29.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A29__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A29.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A29__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A29.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A29__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A3.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A3__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A3.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A3__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A3.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A3__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A30.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A30__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A30.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A30__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A30.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A30__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A31.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A31__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A31.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A31__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A31.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A31__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A32.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A32__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A32.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A32__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A32.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A32__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A33.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A33__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A33.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A33__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A33.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A33__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A34.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A34__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A34.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A34__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A34.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A34__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A35.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A35__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A35.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A35__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A35.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A35__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A36.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A36__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A36.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A36__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A36.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A36__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A37.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A37__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A37.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A37__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A37.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A37__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A38.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A38__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A38.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A38__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A38.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A38__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A39.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A39__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A39.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A39__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A39.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A39__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A4.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A4__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A4.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A4__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A4.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A4__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A40.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A40__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A40.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A40__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A40.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A40__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A41.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A41__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A41.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A41__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A41.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A41__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A42.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A42__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A42.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A42__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A42.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A42__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A43.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A43__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A43.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A43__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A43.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A43__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A44.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A44__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A44.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A44__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A44.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A44__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A45.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A45__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A45.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A45__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A45.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A45__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A46.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A46__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A46.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A46__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A46.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A46__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A47.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A47__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A47.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A47__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A47.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A47__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A48.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A48__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A48.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A48__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A48.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A48__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A49.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A49__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A49.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A49__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A49.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A49__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A5.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A5__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A5.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A5__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A5.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A5__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A50.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A50__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A50.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A50__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A50.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A50__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A51.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A51__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A51.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A51__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A51.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A51__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A52.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A52__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A52.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A52__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A52.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A52__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A53.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A53__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A53.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A53__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A53.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A53__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A54.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A54__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A54.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A54__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A54.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A54__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A55.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A55__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A55.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A55__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A55.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A55__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A56.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A56__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A56.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A56__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A56.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A56__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A57.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A57__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A57.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A57__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A57.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A57__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A58.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A58__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A58.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A58__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A58.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A58__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A59.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A59__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A59.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A59__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A59.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A59__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A6.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A6__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A6.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A6__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A6.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A6__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A60.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A60__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A60.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A60__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A60.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A60__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A61.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A61__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A61.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A61__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A61.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A61__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A62.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A62__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A62.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A62__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A62.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A62__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A7.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A7__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A7.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A7__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A7.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A7__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A8.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A8__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A8.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A8__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A8.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A8__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A9.varInsert(__Vfinal,"a", &(TOP.multiplier__DOT__A9__DOT__a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A9.varInsert(__Vfinal,"b", &(TOP.multiplier__DOT__A9__DOT__b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_multiplier__A9.varInsert(__Vfinal,"sum", &(TOP.multiplier__DOT__A9__DOT__sum), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
    }
}
